### ISSUE TITLE
Garage door stays "open" in HomeKit but pin is closed

### ISSUE THREAD

**Issue by hyperbart** [plhyhc/homebridge-garage-door-wsensor#3] opened 2020-07-09 13:12 UTC
I think i might be encountering a bug:

Raspberry Pi Model B V1.2
Board with 2 relays
homebridge-raspbian-image
Updated to latest versions

The relays work fine but the doorSensorPin seems to be not working in your plugin. If I close/short the pin I can see in the following command that PIN 18 is 1 but Homekit keeps reporting that the garage door is open.

```
pi@homebridge:~ $ gpio readall
 +-----+-----+---------+------+---+---Pi 3B--+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 0 | IN   | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | IN   | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |  OUT | 0 | 11 || 12 | 1 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |  OUT | 1 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 1 | OUT  | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | IN   | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 3B--+---+------+---------+-----+-----+
```

If I open the garage, port 18 becomes 0:
```

pi@homebridge:~ $ gpio readall
 +-----+-----+---------+------+---+---Pi 3B--+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 0 | IN   | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | IN   | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |  OUT | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |  OUT | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 1 | OUT  | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 1 | IN   | CE1     | 11  | 7   |
 |   0 |  30 |   SDA.0 |   IN | 1 | 27 || 28 | 1 | IN   | SCL.0   | 31  | 1   |
 |   5 |  21 | GPIO.21 |   IN | 1 | 29 || 30 |   |      | 0v      |     |     |
 |   6 |  22 | GPIO.22 |   IN | 1 | 31 || 32 | 0 | IN   | GPIO.26 | 26  | 12  |
 |  13 |  23 | GPIO.23 |   IN | 0 | 33 || 34 |   |      | 0v      |     |     |
 |  19 |  24 | GPIO.24 |   IN | 0 | 35 || 36 | 0 | IN   | GPIO.27 | 27  | 16  |
 |  26 |  25 | GPIO.25 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO.28 | 28  | 20  |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO.29 | 29  | 21  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+---Pi 3B--+---+------+---------+-----+-----+
```

Configuration:
`{
    "bridge": {
        "name": "Homebridge 3163",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51495,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [
        {
            "accessory": "Garage Door Opener",
            "name": "Garage Door 1",
            "doorRelayPin": 11,
            "doorSensorPin": 18,
            "invertDoorState": false,
            "invertSensorState": false,
            "duration_ms": 800
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "sudo": true,
            "platform": "config"
        }
    ]
}`

**Comment by plhyhc** [comment] 2020-07-10 00:14
Just making sure, but in your config.json file you set the sensor pin to
18?  Also in the two gpio readall you added to the email, I see 18 is "1"
in both.  Or am I looking in the wrong place?


[image: image.png]

**Comment by hyperbart** [comment] 2020-07-10 07:18
Hi, thanks for your quick reply.
Column V is the one that changes when I close or open the pin, that is the one you should look at.
(there are 2 columns labeled V, the left row and the right row, corresponding with the pin layout of RPI)

**Comment by plhyhc** [comment] 2020-07-11 00:52
Unfortunately not sure what I can say. I use the Pi 3 and it works great. I have it in my garage.

Josh
________________________________

**Comment by hyperbart** [comment] 2020-07-11 11:18
Would you be so kind to reinstall on another SD card and test it with the same version as mine?

I have the feeling it has something to do with different versions or incompatibility.

**Comment by wjstone** [comment] 2020-08-17 04:02
change  "invertSensorState": to false in your config.  Thats what I had to do on mine.

**Comment by AnisBoubaker** [comment] 2021-07-12 17:02
Having the exact same issue here. As soon as I change the doorSensorPin to another pin, it sets the pin in OUTPUT mode, whilst it should be reading... When the magnets closes the circuit, a high signal is sent to the pin and it should change the state. 

I think line 34 of index.js might be at fault : 

```rpio.open(this.doorSensorPin, rpio.OUTPUT, this.gpioSensorVal(this.invertSensorState));```

I can confirm changing this line (OUTPUT for INPUT) solves the problem on my end.

**Comment by nsayer** [comment] 2023-06-05 20:09
This does look like a correct fix to me, but when setting the sensor pin to input, you wouldn't set a value as the third argument to open() like this. You might configure a pull-up or pull-down optionally (which ought to be something available in the config, IMHO).

**Comment by nsayer** [comment] 2023-06-05 20:30
I've opened a PR with a fix for this, and also to allow optionally configuring pull-up or -down on the sensor pin.

**Comment by plhyhc** [comment] 2023-06-09 17:55
@nsayer Thanks for the PR!  This is helpful.  Were you able to test this on a RPi?

**Comment by nsayer** [comment] 2023-06-09 18:14
Not yet. I have boards coming today and intended to try it this afternoon and, if necessary, make adjustments.

**Comment by nsayer** [comment] 2023-06-12 19:47
Ok, I tested it and fixed a syntax error, but as it is now, I think it's good to go.

**Comment by plhyhc** [comment] 2023-07-30 01:32
A new options has been provided by @nsayer to help address this issue.

**Closed as completed by plhyhc** 2023-07-30 01:32 UTC
